#!/usr/bin/env ruby

`git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim` unless File.exists?(File.expand_path("~/.vim/bundle/Vundle.vim"))
%w[vimrc gvimrc .].map { |rc| link("vim/#{rc}") }
