set nocompatible
filetype off
syntax on
set noswapfile

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'Raimondi/delimitMate'
Plugin 'itchyny/lightline.vim'
Plugin 'sjl/badwolf'
Plugin 'tpope/vim-endwise'
Plugin 'Shougo/vimproc.vim'
Plugin 'Shougo/unite.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'henrik/vim-indexed-search'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-commentary'
Plugin 'junegunn/vim-easy-align'

Plugin 'thoughtbot/vim-rspec'
Plugin 'jgdavey/tslime.vim'

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

colorscheme badwolf
let g:badwolf_darkgutter = 1
let g:badwolf_tabline = 0

" Always show the git gutter
let g:gitgutter_sign_column_always = 1

" Show git gutter signs after typing
let g:gitgutter_realtime = 1

" Show line numbers
set number

" Prevent encoding vietnam
set encoding=utf-8

" Wraps and indicates if a line was wrapped
set wrap
set showbreak=↪

" General indentation settings
set ts=2 sts=2 sw=2 expandtab

" Do a smart break of line (do not start at the beginning of the line but on
" the same indentation level)
set breakindent

" Working backspace
set backspace=2

" Turn on indentation based on the file type
filetype plugin indent on

" Intendation without losing visual selection
vmap > >gv
vmap < <gv

" Let the buffer change without saving the current buffer
set hidden

" No beep anymore
set visualbell

" Enable mouse support for all modes
set mouse=a

" j/k working on wrapped lines
noremap j gj
noremap k gk
noremap gj j
noremap gk k

" Easy buffer navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Minimum number of lines above and below the cursor
set scrolloff=5

" Highlight current line
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey20

" Cursor is in the center after search
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" Don't move on *
nnoremap * *<c-o>

" Changing color of matching brackets
hi! link MatchParen Search

" Highlight search
set hlsearch

" Incremental Search please
set incsearch

" Leader needs space
let mapleader = "\<Space>"

" Clear search with <leader><space>
nnoremap <leader><space> :noh<cr>

" Save all with the leader + w
nnoremap <Leader>w :wall<CR>

" Quit vim
nnoremap <Leader>q :q<CR>

" copy visual selection to os clipboard
vmap <Leader>y "+y

" Reload the vimrc
nnoremap <Leader>r :source $MYVIMRC<CR>

" Unite.vim
" Make it a fuzzy CTRL-p alternative
call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <C-p> :Unite buffer file_rec/async:! -start-insert<CR>
nnoremap <C-l> :Unite buffer -start-insert<CR>
call unite#custom#profile('files', 'context.ignorecase', 1)
call unite#custom#profile('files', 'context.smartcase', 0)
call unite#filters#sorter_default#use(['sorter_rank'])
" Using ag as recursive command.
let g:unite_source_rec_async_command = 'ag --follow --nocolor --nogroup --hidden -g ""'

" Grep like search with the silver searcher
let g:unite_source_grep_command = 'ag'
nnoremap <C-o> :Unite grep:.<CR>
let g:unite_source_grep_default_opts =
      \ '--line-numbers --nocolor --nogroup --hidden --ignore ' .
      \ '''.hg'' --ignore ''.svn'' --ignore ''.git'' --ignore ''.bzr'' ' .
      \ '--ignore ''**/*.pyc'''
let g:unite_source_grep_recursive_opt = ''

" Search through yanks
let g:unite_source_history_yank_enable = 1
nnoremap <leader>y :<C-u>Unite history/yank<CR>

" Toggle paste mode
set pastetoggle=<F10>

" Esc 
imap jk <Esc>
let g:multi_cursor_quit_key='jk'

" Substitution is always global
set gdefault

" Rspec stuff
let g:rspec_command = 'call Send_to_Tmux("rspec {spec}\n")'
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

" DelimitMate config
let b:delimitMate_expand_cr=1
let b:delimitMate_expand_space=1

" Correct syntax-highlight for scss files (OSX)
au BufRead,BufNewFile *.scss set filetype=scss

" Ignore a lot of stuff
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/_site/*,*/bower_components/*,*/node_modules/*

" Cursor shape in insert/normal mode
" For tmux running in iTerm2 on OS X
" http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"

" Highlight current column as well
au WinLeave * set nocursorline nocursorcolumn
au WinEnter * set cursorline cursorcolumn
set cursorline cursorcolumn

" aka 'Oh, that's the key I have been hitting by accident'
nnoremap Q <nop>

