execute pathogen#infect()
syntax on

" Show line numbers
set number

" Use Steve Losh's badwolf colorscheme
colorscheme badwolf

" Prevent encoding vietnam
set encoding=utf-8

" Wraps and indicates if a line was wrapped
set wrap
set showbreak=↪

" General indentation settings
set ts=2 sts=2 sw=2 expandtab

" Turn on indentation based on the file type
filetype plugin indent on

" Intendation without losing visual selection
vmap > >gv
vmap < <gv

" Let the buffer change without saving the current buffer
set hidden

" No beep anymore
set visualbell

" Remaping beginning and end of line
noremap H ^
noremap L $

" j/k working on wrapped lines
noremap j gj
noremap k gk
noremap gj j
noremap gk k

" Moving single lines
nmap <M-Up> [e
nmap <M-Down> ]e
nmap <M-k> [e
nmap <M-j> ]e

" Bubble multiple lines
vmap <M-Up> [egv
vmap <M-Down> ]egv
vmap <M-k> [egv
vmap <M-j> ]egv

" Easy buffer navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Minimum number of lines above and below the cursor
set scrolloff=5

" Highlight current line
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey20

" Cursor is in the center after search
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" Don't move on *
nnoremap * *<c-o>

" Hightlight text which goes over 80 columns
" highlight OverLength ctermbg=red ctermfg=white guibg=#592929
" match OverLength /\%81v.\+/

" Changing color of matching brackets
hi! link MatchParen Search

" Highlight search
set hlsearch

" Clear search with <leader><space>
nnoremap <leader><space> :noh<cr>

" Clear search with escape key
nnoremap <esc> :noh<cr><esc>

" Substitution is always global
set gdefault

" Save when losing focus
au FocusLost * :silent! wall

" Correct syntax-highlight for scss files (OSX)
au BufRead,BufNewFile *.scss set filetype=scss

" Change shape of cursor depending on mode (This is for tmux inside iTerm2)
let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"

" Enabled for ruby-blocks plugin
" runtime macros/matchit.vim
