set nocompatible
filetype off
syntax on
set noswapfile

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'Raimondi/delimitMate'
Plugin 'bling/vim-airline'
Plugin 'sjl/badwolf'
Plugin 'tpope/vim-endwise'
Plugin 'Shougo/unite.vim'
Plugin 'scrooloose/nerdcommenter.git'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

colorscheme badwolf

" Show line numbers
set number

" Prevent encoding vietnam
set encoding=utf-8

" Wraps and indicates if a line was wrapped
set wrap
set showbreak=↪

" General indentation settings
set ts=2 sts=2 sw=2 expandtab

" Working backspace
set backspace=2

" Turn on indentation based on the file type
filetype plugin indent on

" Intendation without losing visual selection
vmap > >gv
vmap < <gv

" Let the buffer change without saving the current buffer
set hidden

" No beep anymore
set visualbell

" j/k working on wrapped lines
noremap j gj
noremap k gk
noremap gj j
noremap gk k

" Easy buffer navigation
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l

" Minimum number of lines above and below the cursor
set scrolloff=5

" Highlight current line
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey20

" Cursor is in the center after search
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" Don't move on *
nnoremap * *<c-o>

" Changing color of matching brackets
hi! link MatchParen Search

" Mark 81th line
highlight ColorColumn ctermbg=red
call matchadd('ColorColumn', '\%81v', 100)

" Highlight search
set hlsearch

" Leader needs space
let mapleader = "\<Space>"

" Clear search with <leader><space>
nnoremap <leader><space> :noh<cr>

" Save all with the leader + w
nnoremap <Leader>w :wall<CR>

" Quit vim
nnoremap <Leader>q :q<CR>

" copy visual selection to os clipboard
vmap <Leader>y "+y

" Reload the vimrc
nnoremap <Leader>r :source $MYVIMRC<CR>

" Unite.vim
call unite#filters#matcher_default#use(['matcher_fuzzy'])
nnoremap <C-p> :Unite file_rec buffer -start-insert<CR>
call unite#custom#profile('files', 'context.ignorecase', 1)
call unite#custom#profile('files', 'context.smartcase', 0)

" Toggle paste mode
set pastetoggle=<F10>

" Esc 
imap jk <Esc>

" Substitution is always global
set gdefault

" DelimitMate config
let b:delimitMate_expand_cr=1
let b:delimitMate_expand_space=1

" vim-airline
set laststatus=2
set ttimeoutlen=50
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled = 1

" Correct syntax-highlight for scss files (OSX)
au BufRead,BufNewFile *.scss set filetype=scss

" Ignore a lot of stuff
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/_site/*,*/bower_components/*,*/node_modules/*

" Cursor shape in insert/normal mode
" For tmux running in iTerm2 on OS X
" http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"

" Highlight current column as well
au WinLeave * set nocursorline nocursorcolumn
au WinEnter * set cursorline cursorcolumn
set cursorline cursorcolumn

" aka 'Oh, that's the key I have been hitting by accident'
nnoremap Q <nop>

